version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  bloodbuddy:
    build: .
    container_name: bloodbuddy-app
    ports:
      - "8501:8501"
    environment:
      - ELASTIC_HOST=http://elasticsearch:9200
    volumes:
      - ./user_profiles.json:/app/user_profiles.json
      - ./sfondo.png:/app/sfondo.png  
    depends_on:
      - elasticsearch
    restart: unless-stopped
    command: streamlit run app1.py --server.port=8501 --server.address=0.0.0.0

volumes:
  esdata:
